version: "3.9"

services:
  todomir:
    image: todomir 
    build: .
    environment:
      - DJANGO_SECRET=secret
      - DEBUG=true
      - ALLOWED_HOSTS=localhost
      - TRUSTED_ORIGINS=http://localhost:8080
      - DB_PATH=/srv/db/db.sqlite3
    ports:
      - "8080:8000"
    volumes:
      - todomir_db:/srv/db/

  celery-worker:
    image: todomir 
    command: celery-worker 
    environment:
      - DJANGO_SECRET=secret
      - DEBUG=false
      - DB_PATH=/srv/db/db.sqlite3
    volumes:
      - todomir_db:/srv/db/

  celery-beat:
    image: todomir 
    command: celery-beat
    environment:
      - DJANGO_SECRET=secret
      - DEBUG=false
      - DB_PATH=/srv/db/db.sqlite3
    volumes:
      - todomir_db:/srv/db/

  redis:
    image: redis:latest
    expose: ["6379"]

volumes:
  todomir_db:
