# Generated by Django 5.0.2 on 2024-02-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_alter_todotask_completed_alter_todotask_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotask",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="todotask",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="todos.todotaskschedule",
            ),
        ),
    ]
