# Generated by Django 5.0.2 on 2024-02-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todotask_external_id_alter_todotask_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
