# Generated by Django 5.0.2 on 2024-03-04 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppinglistitem",
            options={"ordering": ("completed", "-created")},
        ),
    ]
